[I 2023-08-29 10:16:52.495 ServerApp] Package notebook took 0.0000s to import
[I 2023-08-29 10:16:52.507 ServerApp] Package jupyter_lsp took 0.0110s to import
[W 2023-08-29 10:16:52.507 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-29 10:16:52.512 ServerApp] Package jupyter_server_terminals took 0.0049s to import
[I 2023-08-29 10:16:52.513 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-29 10:16:52.542 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-29 10:16:52.543 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-29 10:16:52.543 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-29 10:16:52.548 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-29 10:16:52.553 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-29 10:16:52.558 ServerApp] notebook | extension was successfully linked.
[I 2023-08-29 10:16:52.770 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-29 10:16:52.815 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-29 10:16:52.817 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-29 10:16:52.818 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-29 10:16:52.819 LabApp] JupyterLab extension loaded from /home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyterlab
[I 2023-08-29 10:16:52.820 LabApp] JupyterLab application directory is /home/ubuntu/HealthRisk-AI/myenv/share/jupyter/lab
[I 2023-08-29 10:16:52.820 LabApp] Extension Manager is 'pypi'.
[I 2023-08-29 10:16:52.823 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-29 10:16:52.826 ServerApp] notebook | extension was successfully loaded.
[I 2023-08-29 10:16:52.826 ServerApp] Serving notebooks from local directory: /home/ubuntu/HealthRisk-AI/api/ml_model
[I 2023-08-29 10:16:52.826 ServerApp] Jupyter Server 2.7.2 is running at:
[I 2023-08-29 10:16:52.826 ServerApp] http://ip-172-31-18-128:8888/tree?token=e1b9abc0b3f46812db050b93426c727cb9f691e5e1550908
[I 2023-08-29 10:16:52.826 ServerApp]     http://127.0.0.1:8888/tree?token=e1b9abc0b3f46812db050b93426c727cb9f691e5e1550908
[I 2023-08-29 10:16:52.826 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-08-29 10:16:52.830 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2023-08-29 10:16:52.830 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/ubuntu/.local/share/jupyter/runtime/jpserver-1217-open.html
    Or copy and paste one of these URLs:
        http://ip-172-31-18-128:8888/tree?token=e1b9abc0b3f46812db050b93426c727cb9f691e5e1550908
        http://127.0.0.1:8888/tree?token=e1b9abc0b3f46812db050b93426c727cb9f691e5e1550908
[I 2023-08-29 10:16:52.847 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-08-29 10:17:04.537 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304223367 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:04.537 ServerApp] wrote error: 'Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154'
    Traceback (most recent call last):
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 73, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 501, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 532, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154)
[W 2023-08-29 10:17:04.541 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304223367 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 4.71ms referer=http://13.215.190.122:8888/notebooks/main.ipynb
[W 2023-08-29 10:17:05.537 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:05.562 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 25.90ms referer=None
[W 2023-08-29 10:17:05.718 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304224693 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:05.718 ServerApp] wrote error: 'Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154'
    Traceback (most recent call last):
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 73, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 501, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 532, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154)
[W 2023-08-29 10:17:05.719 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304224693 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 1.33ms referer=http://13.215.190.122:8888/notebooks/main.ipynb
[W 2023-08-29 10:17:09.633 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:09.634 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 1.49ms referer=None
[W 2023-08-29 10:17:09.794 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304228769 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:09.794 ServerApp] wrote error: 'Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154'
    Traceback (most recent call last):
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 73, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 501, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 532, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154)
[W 2023-08-29 10:17:09.794 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304228769 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 1.33ms referer=http://13.215.190.122:8888/notebooks/main.ipynb
[W 2023-08-29 10:17:16.530 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:16.530 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154/channels?session_id=7119fdb5-815d-4cd2-8b07-3233da32a890 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 1.47ms referer=None
[W 2023-08-29 10:17:16.681 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304235659 (39.47.106.175): Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154
[W 2023-08-29 10:17:16.681 ServerApp] wrote error: 'Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154'
    Traceback (most recent call last):
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 73, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 501, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/ubuntu/HealthRisk-AI/myenv/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 532, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: d4a425d1-0ab1-48ec-91e8-3dda06524154)
[W 2023-08-29 10:17:16.682 ServerApp] 404 GET /api/kernels/d4a425d1-0ab1-48ec-91e8-3dda06524154?1693304235659 (4a6e7f0113f54a65936eca77e6390598@39.47.106.175) 1.40ms referer=http://13.215.190.122:8888/notebooks/main.ipynb
[I 2023-08-29 10:17:20.032 ServerApp] Interrupted...
